/* ============================================================
   Respite · renames.js · Where the old keys went
   ------------------------------------------------------------
   Names and ids used to be allowed to drift apart: RENAMED pinned
   a key while the name above it changed, so Gloam Ore answered to
   "cold" and Gnarl Wood to "iron". That bought safety and cost
   legibility, and every tool that rebuilt an id from a name -- the
   test harness did, quietly, for months -- got it wrong.

   Schema 12 closes the gap. An id is the first word of the name,
   always, and this map carries every key that moved on the day it
   closed. 386 of them.

   It is read once, by migrate12 in state.js, against a save that
   has not been opened since. Nothing else should need it: a key
   that still needs translating at runtime is a bug somewhere else.

   Renaming a material from here on means a new map and a new
   schema step. That is the point -- the cost is visible now.
   ============================================================ */

export const MOVED_KEYS = Object.freeze({
  // abyssal -> hoard
  abyssal_amulet: "hoard_amulet",
  abyssal_clasp: "hoard_clasp",
  abyssal_dredge: "hoard_dredge",
  abyssal_grimoire: "hoard_grimoire",
  abyssal_inlay: "hoard_inlay",
  abyssal_net: "hoard_net",
  abyssal_staff: "hoard_staff",
  // blood -> amber
  blood_amulet: "amber_amulet",
  blood_clasp: "amber_clasp",
  blood_dredge: "amber_dredge",
  blood_grimoire: "amber_grimoire",
  blood_inlay: "amber_inlay",
  blood_net: "amber_net",
  blood_staff: "amber_staff",
  // bog -> mire
  bog_bar: "mire_bar",
  bog_blade: "mire_blade",
  bog_chest: "mire_chest",
  bog_dagger: "mire_dagger",
  bog_delve: "mire_delve",
  bog_gblade: "mire_gblade",
  bog_greatsword: "mire_greatsword",
  bog_hboots: "mire_hboots",
  bog_head: "mire_head",
  bog_helm: "mire_helm",
  bog_hgaunts: "mire_hgaunts",
  bog_pick: "mire_pick",
  bog_ring: "mire_ring",
  bog_sword: "mire_sword",
  // cave -> chalk
  cave_amulet: "chalk_amulet",
  cave_clasp: "chalk_clasp",
  cave_dredge: "chalk_dredge",
  cave_grimoire: "chalk_grimoire",
  cave_inlay: "chalk_inlay",
  cave_net: "chalk_net",
  cave_staff: "chalk_staff",
  // chitin -> stag
  chitin_bind: "stag_bind",
  chitin_flay: "stag_flay",
  chitin_grip: "stag_grip",
  chitin_hood: "stag_hood",
  chitin_jacket: "stag_jacket",
  chitin_knife: "stag_knife",
  chitin_leather: "stag_leather",
  chitin_mboots: "stag_mboots",
  chitin_mgloves: "stag_mgloves",
  // cold -> rime
  cold_bar: "rime_bar",
  cold_blade: "rime_blade",
  cold_chest: "rime_chest",
  cold_dagger: "rime_dagger",
  cold_delve: "rime_delve",
  cold_gblade: "rime_gblade",
  cold_greatsword: "rime_greatsword",
  cold_hboots: "rime_hboots",
  cold_head: "rime_head",
  cold_helm: "rime_helm",
  cold_hgaunts: "rime_hgaunts",
  cold_pick: "rime_pick",
  cold_ring: "rime_ring",
  cold_sword: "rime_sword",
  // craft -> craft
  craft_abyssal_amulet: "craft_hoard_amulet",
  craft_abyssal_clasp: "craft_hoard_clasp",
  craft_abyssal_inlay: "craft_hoard_inlay",
  craft_abyssal_net: "craft_hoard_net",
  craft_abyssal_staff: "craft_hoard_staff",
  craft_blood_amulet: "craft_amber_amulet",
  craft_blood_clasp: "craft_amber_clasp",
  craft_blood_inlay: "craft_amber_inlay",
  craft_blood_net: "craft_amber_net",
  craft_blood_staff: "craft_amber_staff",
  craft_bog_bar: "craft_mire_bar",
  craft_bog_blade: "craft_mire_blade",
  craft_bog_chest: "craft_mire_chest",
  craft_bog_dagger: "craft_mire_dagger",
  craft_bog_hboots: "craft_mire_hboots",
  craft_bog_head: "craft_mire_head",
  craft_bog_helm: "craft_mire_helm",
  craft_bog_hgaunts: "craft_mire_hgaunts",
  craft_bog_pick: "craft_mire_pick",
  craft_bog_ring: "craft_mire_ring",
  craft_bog_sword: "craft_mire_sword",
  craft_cave_amulet: "craft_chalk_amulet",
  craft_cave_clasp: "craft_chalk_clasp",
  craft_cave_inlay: "craft_chalk_inlay",
  craft_cave_net: "craft_chalk_net",
  craft_cave_staff: "craft_chalk_staff",
  craft_chitin_bind: "craft_stag_bind",
  craft_chitin_grip: "craft_stag_grip",
  craft_chitin_hood: "craft_stag_hood",
  craft_chitin_jacket: "craft_stag_jacket",
  craft_chitin_knife: "craft_stag_knife",
  craft_chitin_leather: "craft_stag_leather",
  craft_chitin_mboots: "craft_stag_mboots",
  craft_chitin_mgloves: "craft_stag_mgloves",
  craft_cold_bar: "craft_rime_bar",
  craft_cold_blade: "craft_rime_blade",
  craft_cold_chest: "craft_rime_chest",
  craft_cold_dagger: "craft_rime_dagger",
  craft_cold_hboots: "craft_rime_hboots",
  craft_cold_head: "craft_rime_head",
  craft_cold_helm: "craft_rime_helm",
  craft_cold_hgaunts: "craft_rime_hgaunts",
  craft_cold_pick: "craft_rime_pick",
  craft_cold_ring: "craft_rime_ring",
  craft_cold_sword: "craft_rime_sword",
  craft_cured_bind: "craft_gaunt_bind",
  craft_cured_grip: "craft_gaunt_grip",
  craft_cured_hood: "craft_gaunt_hood",
  craft_cured_jacket: "craft_gaunt_jacket",
  craft_cured_knife: "craft_gaunt_knife",
  craft_cured_leather: "craft_gaunt_leather",
  craft_cured_mboots: "craft_gaunt_mboots",
  craft_cured_mgloves: "craft_gaunt_mgloves",
  craft_dragon_hood: "craft_lantern_hood",
  craft_dragon_lboots: "craft_lantern_lboots",
  craft_dragon_lgloves: "craft_lantern_lgloves",
  craft_dragon_robe: "craft_lantern_robe",
  craft_dragon_sickle: "craft_lantern_sickle",
  craft_dragon_string: "craft_lantern_string",
  craft_dragon_weave: "craft_lantern_weave",
  craft_godsdown_axe: "craft_marrow_axe",
  craft_godsdown_bow: "craft_marrow_bow",
  craft_godsdown_handle: "craft_marrow_handle",
  craft_godsdown_plank: "craft_marrow_plank",
  craft_godsdown_score: "craft_marrow_score",
  craft_godsdown_shaft: "craft_marrow_shaft",
  craft_godsdown_shield: "craft_marrow_shield",
  craft_godsdown_stave: "craft_marrow_stave",
  craft_grave_hood: "craft_noose_hood",
  craft_grave_lboots: "craft_noose_lboots",
  craft_grave_lgloves: "craft_noose_lgloves",
  craft_grave_robe: "craft_noose_robe",
  craft_grave_sickle: "craft_noose_sickle",
  craft_grave_string: "craft_noose_string",
  craft_grave_weave: "craft_noose_weave",
  craft_iron_axe: "craft_gnarl_axe",
  craft_iron_bow: "craft_gnarl_bow",
  craft_iron_handle: "craft_gnarl_handle",
  craft_iron_plank: "craft_gnarl_plank",
  craft_iron_score: "craft_gnarl_score",
  craft_iron_shaft: "craft_gnarl_shaft",
  craft_iron_shield: "craft_gnarl_shield",
  craft_iron_stave: "craft_gnarl_stave",
  craft_leviathan_amulet: "craft_sunken_amulet",
  craft_leviathan_clasp: "craft_sunken_clasp",
  craft_leviathan_inlay: "craft_sunken_inlay",
  craft_leviathan_net: "craft_sunken_net",
  craft_leviathan_staff: "craft_sunken_staff",
  craft_river_amulet: "craft_bog_amulet",
  craft_river_clasp: "craft_bog_clasp",
  craft_river_inlay: "craft_bog_inlay",
  craft_river_net: "craft_bog_net",
  craft_river_staff: "craft_bog_staff",
  craft_scaled_bind: "craft_slough_bind",
  craft_scaled_grip: "craft_slough_grip",
  craft_scaled_hood: "craft_slough_hood",
  craft_scaled_jacket: "craft_slough_jacket",
  craft_scaled_knife: "craft_slough_knife",
  craft_scaled_leather: "craft_slough_leather",
  craft_scaled_mboots: "craft_slough_mboots",
  craft_scaled_mgloves: "craft_slough_mgloves",
  craft_star_bar: "craft_starfall_bar",
  craft_star_blade: "craft_starfall_blade",
  craft_star_chest: "craft_starfall_chest",
  craft_star_dagger: "craft_starfall_dagger",
  craft_star_hboots: "craft_starfall_hboots",
  craft_star_head: "craft_starfall_head",
  craft_star_helm: "craft_starfall_helm",
  craft_star_hgaunts: "craft_starfall_hgaunts",
  craft_star_pick: "craft_starfall_pick",
  craft_star_ring: "craft_starfall_ring",
  craft_star_sword: "craft_starfall_sword",
  craft_umber_axe: "craft_elder_axe",
  craft_umber_bow: "craft_elder_bow",
  craft_umber_handle: "craft_elder_handle",
  craft_umber_plank: "craft_elder_plank",
  craft_umber_score: "craft_elder_score",
  craft_umber_shaft: "craft_elder_shaft",
  craft_umber_shield: "craft_elder_shield",
  craft_umber_stave: "craft_elder_stave",
  craft_void_amulet: "craft_idol_amulet",
  craft_void_axe: "craft_wither_axe",
  craft_void_bar: "craft_hollow_bar",
  craft_void_blade: "craft_hollow_blade",
  craft_void_bow: "craft_wither_bow",
  craft_void_chest: "craft_hollow_chest",
  craft_void_clasp: "craft_idol_clasp",
  craft_void_dagger: "craft_hollow_dagger",
  craft_void_handle: "craft_wither_handle",
  craft_void_hboots: "craft_hollow_hboots",
  craft_void_head: "craft_hollow_head",
  craft_void_helm: "craft_hollow_helm",
  craft_void_hgaunts: "craft_hollow_hgaunts",
  craft_void_inlay: "craft_idol_inlay",
  craft_void_net: "craft_idol_net",
  craft_void_pick: "craft_hollow_pick",
  craft_void_plank: "craft_wither_plank",
  craft_void_ring: "craft_hollow_ring",
  craft_void_score: "craft_wither_score",
  craft_void_shaft: "craft_wither_shaft",
  craft_void_shield: "craft_wither_shield",
  craft_void_staff: "craft_idol_staff",
  craft_void_stave: "craft_wither_stave",
  craft_void_sword: "craft_hollow_sword",
  craft_widows_hood: "craft_widow_hood",
  craft_widows_lboots: "craft_widow_lboots",
  craft_widows_lgloves: "craft_widow_lgloves",
  craft_widows_robe: "craft_widow_robe",
  craft_widows_sickle: "craft_widow_sickle",
  craft_widows_string: "craft_widow_string",
  craft_widows_weave: "craft_widow_weave",
  craft_wyrm_axe: "craft_ember_axe",
  craft_wyrm_bar: "craft_wyrmheart_bar",
  craft_wyrm_blade: "craft_wyrmheart_blade",
  craft_wyrm_bow: "craft_ember_bow",
  craft_wyrm_chest: "craft_wyrmheart_chest",
  craft_wyrm_dagger: "craft_wyrmheart_dagger",
  craft_wyrm_handle: "craft_ember_handle",
  craft_wyrm_hboots: "craft_wyrmheart_hboots",
  craft_wyrm_head: "craft_wyrmheart_head",
  craft_wyrm_helm: "craft_wyrmheart_helm",
  craft_wyrm_hgaunts: "craft_wyrmheart_hgaunts",
  craft_wyrm_pick: "craft_wyrmheart_pick",
  craft_wyrm_plank: "craft_ember_plank",
  craft_wyrm_ring: "craft_wyrmheart_ring",
  craft_wyrm_score: "craft_ember_score",
  craft_wyrm_shaft: "craft_ember_shaft",
  craft_wyrm_shield: "craft_ember_shield",
  craft_wyrm_stave: "craft_ember_stave",
  craft_wyrm_sword: "craft_wyrmheart_sword",
  // cured -> gaunt
  cured_bind: "gaunt_bind",
  cured_flay: "gaunt_flay",
  cured_grip: "gaunt_grip",
  cured_hood: "gaunt_hood",
  cured_jacket: "gaunt_jacket",
  cured_knife: "gaunt_knife",
  cured_leather: "gaunt_leather",
  cured_mboots: "gaunt_mboots",
  cured_mgloves: "gaunt_mgloves",
  // dragon -> lantern
  dragon_book: "lantern_book",
  dragon_harvest: "lantern_harvest",
  dragon_hood: "lantern_hood",
  dragon_lboots: "lantern_lboots",
  dragon_lgloves: "lantern_lgloves",
  dragon_robe: "lantern_robe",
  dragon_sickle: "lantern_sickle",
  dragon_string: "lantern_string",
  dragon_weave: "lantern_weave",
  // godsdown -> marrow
  godsdown_axe: "marrow_axe",
  godsdown_bow: "marrow_bow",
  godsdown_fell: "marrow_fell",
  godsdown_ggrip: "marrow_ggrip",
  godsdown_handle: "marrow_handle",
  godsdown_plank: "marrow_plank",
  godsdown_score: "marrow_score",
  godsdown_shaft: "marrow_shaft",
  godsdown_shield: "marrow_shield",
  godsdown_stave: "marrow_stave",
  // grave -> noose
  grave_book: "noose_book",
  grave_harvest: "noose_harvest",
  grave_hood: "noose_hood",
  grave_lboots: "noose_lboots",
  grave_lgloves: "noose_lgloves",
  grave_robe: "noose_robe",
  grave_sickle: "noose_sickle",
  grave_string: "noose_string",
  grave_weave: "noose_weave",
  // iron -> gnarl
  iron_axe: "gnarl_axe",
  iron_bow: "gnarl_bow",
  iron_fell: "gnarl_fell",
  iron_ggrip: "gnarl_ggrip",
  iron_handle: "gnarl_handle",
  iron_plank: "gnarl_plank",
  iron_score: "gnarl_score",
  iron_shaft: "gnarl_shaft",
  iron_shield: "gnarl_shield",
  iron_stave: "gnarl_stave",
  // leviathan -> sunken
  leviathan_amulet: "sunken_amulet",
  leviathan_clasp: "sunken_clasp",
  leviathan_dredge: "sunken_dredge",
  leviathan_grimoire: "sunken_grimoire",
  leviathan_inlay: "sunken_inlay",
  leviathan_net: "sunken_net",
  leviathan_staff: "sunken_staff",
  // river -> bog
  river_amulet: "bog_amulet",
  river_clasp: "bog_clasp",
  river_dredge: "bog_dredge",
  river_grimoire: "bog_grimoire",
  river_inlay: "bog_inlay",
  river_net: "bog_net",
  river_staff: "bog_staff",
  // scaled -> slough
  scaled_bind: "slough_bind",
  scaled_flay: "slough_flay",
  scaled_grip: "slough_grip",
  scaled_hood: "slough_hood",
  scaled_jacket: "slough_jacket",
  scaled_knife: "slough_knife",
  scaled_leather: "slough_leather",
  scaled_mboots: "slough_mboots",
  scaled_mgloves: "slough_mgloves",
  // star -> starfall
  star_bar: "starfall_bar",
  star_blade: "starfall_blade",
  star_chest: "starfall_chest",
  star_dagger: "starfall_dagger",
  star_delve: "starfall_delve",
  star_gblade: "starfall_gblade",
  star_greatsword: "starfall_greatsword",
  star_hboots: "starfall_hboots",
  star_head: "starfall_head",
  star_helm: "starfall_helm",
  star_hgaunts: "starfall_hgaunts",
  star_pick: "starfall_pick",
  star_ring: "starfall_ring",
  star_sword: "starfall_sword",
  // umber -> elder
  umber_axe: "elder_axe",
  umber_bow: "elder_bow",
  umber_fell: "elder_fell",
  umber_ggrip: "elder_ggrip",
  umber_handle: "elder_handle",
  umber_plank: "elder_plank",
  umber_score: "elder_score",
  umber_shaft: "elder_shaft",
  umber_shield: "elder_shield",
  umber_stave: "elder_stave",
  // void -> hollow
  void_bar: "hollow_bar",
  void_blade: "hollow_blade",
  void_chest: "hollow_chest",
  void_dagger: "hollow_dagger",
  void_delve: "hollow_delve",
  void_gblade: "hollow_gblade",
  void_greatsword: "hollow_greatsword",
  void_hboots: "hollow_hboots",
  void_head: "hollow_head",
  void_helm: "hollow_helm",
  void_hgaunts: "hollow_hgaunts",
  void_pick: "hollow_pick",
  void_ring: "hollow_ring",
  void_sword: "hollow_sword",
  // void -> idol
  void_amulet: "idol_amulet",
  void_clasp: "idol_clasp",
  void_dredge: "idol_dredge",
  void_grimoire: "idol_grimoire",
  void_inlay: "idol_inlay",
  void_net: "idol_net",
  void_staff: "idol_staff",
  // void -> wither
  void_axe: "wither_axe",
  void_bow: "wither_bow",
  void_fell: "wither_fell",
  void_ggrip: "wither_ggrip",
  void_handle: "wither_handle",
  void_plank: "wither_plank",
  void_score: "wither_score",
  void_shaft: "wither_shaft",
  void_shield: "wither_shield",
  void_stave: "wither_stave",
  // widows -> widow
  widows_book: "widow_book",
  widows_harvest: "widow_harvest",
  widows_hood: "widow_hood",
  widows_lboots: "widow_lboots",
  widows_lgloves: "widow_lgloves",
  widows_robe: "widow_robe",
  widows_sickle: "widow_sickle",
  widows_string: "widow_string",
  widows_weave: "widow_weave",
  // wyrm -> ember
  wyrm_axe: "ember_axe",
  wyrm_bow: "ember_bow",
  wyrm_fell: "ember_fell",
  wyrm_ggrip: "ember_ggrip",
  wyrm_handle: "ember_handle",
  wyrm_plank: "ember_plank",
  wyrm_score: "ember_score",
  wyrm_shaft: "ember_shaft",
  wyrm_shield: "ember_shield",
  wyrm_stave: "ember_stave",
  // wyrm -> wyrmheart
  wyrm_bar: "wyrmheart_bar",
  wyrm_blade: "wyrmheart_blade",
  wyrm_chest: "wyrmheart_chest",
  wyrm_dagger: "wyrmheart_dagger",
  wyrm_delve: "wyrmheart_delve",
  wyrm_gblade: "wyrmheart_gblade",
  wyrm_greatsword: "wyrmheart_greatsword",
  wyrm_hboots: "wyrmheart_hboots",
  wyrm_head: "wyrmheart_head",
  wyrm_helm: "wyrmheart_helm",
  wyrm_hgaunts: "wyrmheart_hgaunts",
  wyrm_pick: "wyrmheart_pick",
  wyrm_ring: "wyrmheart_ring",
  wyrm_sword: "wyrmheart_sword",
});

/* A stored key is either a bare id ("slag_bar") or the gear grammar
   ("slag_sword|rare|c17.42|+7"), whose base is the first field. Anything
   unrecognised comes back untouched: a key this map has never heard of is
   either already current or was never ours. */
export function moveKey(key) {
  if (typeof key !== "string" || !key) return key;
  const bar = key.indexOf("|");
  if (bar < 0) return MOVED_KEYS[key] || key;
  const base = key.slice(0, bar);
  const moved = MOVED_KEYS[base];
  return moved ? moved + key.slice(bar) : key;
}
